rpm/setup

It seems that `sed` uses current locale for character collation when doing regexes. It happens that in my locale (Estonian) the leter "z" is positioned right after "s" in the alphabet, so the setup script always fails as "centos" is not mathced for `[a-z]+` ("t" comes after "z" in the alphabet). If I use `[[:alpha:]]` instead of `[a-z]` the script succeeds.
Distro: centos-release-6-6.el6.centos.12.2.x86_64
Locale: Estonian

Change a-z regex to [:alpha:] in the rpm setup

---

deb/setup
deb/setup_0.10
deb/setup_0.12
deb/setup_dev
deb/setup_iojs_1.x
deb/src/_setup.sh
deb/src/build.sh
rpm/test.sh

adds a deb/src/ directory with a `build.sh` script that takes `_setup.sh` and creates a bunch of `setup*` scripts to be pushed to deb.nodesource.com pointing to the new repo locations:
* `setup` -> https://deb.nodesource.com/node010 (legacy script name support)
* `setup_dev` -> https://deb.nodesource.com/node012 (legacy script name support, we can push them on to 0.13 if it appears)
* `setup_0.10` -> https://deb.nodesource.com/node010
* `setup_0.12` -> https://deb.nodesource.com/node012
I'm also imaging:
* `setup_iojs` - follow the latest io.js release, no matter what version (less dramatic upgrades)
* `setup_iojs_1.6` - if, for example, 1.6.\* becomes an LTS release branch for io.js we set up a script just for tracking patch releases on that.

new setup scripts for new repo locations

---

README.md
deb/setup
deb/setup_0.10
deb/setup_0.12
deb/setup_dev
deb/setup_iojs_1.x
deb/setup_iojs_2.x
deb/src/_setup.sh

Adds a few more supported distributions:
+ Linux Mint 17.2, via Ubuntu 14.04 LTS (Fixes #99)
+ BOSS 5, via Debian 7 (Fixes #26) 
Also updates README accordingly:
+ Adds Linux Mint 17.2 "Rafaela"
+ Adds BOSS 5 "Anokha"
+ Adds Fedora 21 "Twenty One"
(FWIW, I also confirmed dists are working via VM.)

update supported distributions

---

README.md

The readme had `sudo apt-get install -y nodejs` as the command for installing iojs, this actually installed node version 0.10.x rather than iojs version 1.x or 2.x

 Corrects iojs install instructions in the readme

---

deb/src/_setup.sh

This adds installation support of node in Kali Linux 2.0, a Debian Jessie based distro.

Add Kali Linux 2 support

---

deb/setup_4.x

Include Kali Linux 2.0 distro as a Debian Jessie derivate

Include Kali Linux 2.0

---

test/test

Currently, the test script doesn't work quite as intended if (for whatever reason) someone is in a path containing a space.

Support paths with spaces

---

README.md

This PR fixes a broken link in README.md to the N|Solid product page at nodesource.com.

Fix broken link to N|Solid product page

---

README.md

Just some minor documentation improvements for the manual installation instructions for Debian based distributions. In particular, add `sudo` where appropriate to the sample commands. Being code blocks almost everyone is just going to copy/paste what's there, and they typically won't be running as `root`, so we should provide commands that will actually work without tweaking. Also uses `lsb_release` to set the correct distribution codename for the `echo` into `sources.list.d` alongside other minor improvements.

Clean-up manual installation instructions for Debian distributions

---

deb/src/_setup.sh

Didnt know the 'buster' repo was also available on nodesource, its better since SparkyLinux is a 'TESTING' based distro. (The Jessie repo does also work fine though, so no hurry)

Changed repository

---

test/test.yarn

Same as `test` but you can do: `curl -sL https://deb.nodesource.com/test.yarn | bash -` and it'll test your Node & Yarn installations rather than Node & npm.

added test.yarn script

---

deb/setup
deb/setup_0.10
deb/setup_0.12
deb/setup_10.x
deb/setup_4.x
deb/setup_5.x
deb/setup_6.x
deb/setup_7.x
deb/setup_8.x
deb/setup_9.x
deb/setup_dev
deb/setup_iojs_1.x
deb/setup_iojs_2.x
deb/setup_iojs_3.x
deb/src/_setup.sh
deb/src/build.sh
rpm/setup
rpm/setup_0.10
rpm/setup_0.12
rpm/setup_10.x
rpm/setup_4.x
rpm/setup_5.x
rpm/setup_6.x
rpm/setup_7.x
rpm/setup_9.x
rpm/setup_iojs_1.x
rpm/setup_iojs_2.x
rpm/setup_iojs_3.x
rpm/src/_setup.sh
rpm/src/build.sh

* deprecate 0.10, 0.12, 4, 7 (single deprecation warning—note that 4 still has a week to go so this is a little bit early)
* add Yarn instructions
* drop `v` from version identifiers
* assume sudo is available (post-wheezy this is a good bet)
deprecation:
deb final instructions:
rpm final instructions:

deprecate old, introduce 10, add Yarn instructions

---

deb/setup
deb/setup_0.10
deb/setup_0.12
deb/setup_10.x
deb/setup_11.x
deb/setup_4.x
deb/setup_5.x
deb/setup_6.x
deb/setup_7.x
deb/setup_8.x
deb/setup_9.x
deb/setup_dev
deb/setup_iojs_1.x
deb/setup_iojs_2.x
deb/setup_iojs_3.x
deb/src/_setup.sh

Debian slim docker images have `apt-key` but not `gnupg` so `apt-key add` fails
Originally reported @ https://github.com/nodejs/nodejs.org/issues/1905, the `php:7` which builds on `debian:stretch-slim` fails the install script because there's no `gnupg`. On Ubuntu it comes from `apt-add-key` which depends on both `apt` (which has `apt-key`) and `gnupg` which is installed on Ubuntu by default I think. On non-slim Debian images it's there too as a default package, but it was stripped out by slim and `apt-key` is there but I guess `apt-key add` isn't intended to work out of the box.
@chrislea over to you

deb: install gnupg package if it's not there

---

rpm/setup_10.x
rpm/setup_11.x
rpm/setup_12.x

This is needed to support Fedora 30

Add -common to regex when searching for rpm distros

---

deb/src/_setup.sh

Ubilinux dolcetto is compatible with Debian stretch. 
Already installed and test with success.

Add support for Ubilinux dolcetto

---

README.md

Minor improvement. Some folks may be more familiar with the version number than the codename.

README: Add version numbers to elementary OS

---

README.md

Korora has been discontinued see https://web.archive.org/web/20180506065306/https://kororaproject.org/about/news/time-for-a-break

 Remove note about discontinued Linux OS Korora

---

deb/setup
deb/setup_0.10
deb/setup_0.12
deb/setup_10.x
deb/setup_11.x
deb/setup_12.x
deb/setup_13.x
deb/setup_14.x
deb/setup_15.x
deb/setup_4.x
deb/setup_5.x
deb/setup_6.x
deb/setup_7.x
deb/setup_8.x
deb/setup_9.x
deb/setup_current.x
deb/setup_dev
deb/setup_iojs_1.x
deb/setup_iojs_2.x
deb/setup_iojs_3.x
deb/setup_lts.x
deb/src/_setup.sh

According to [the documentation of Kali](https://www.kali.org/docs/policy/kali-linux-relationship-with-debian/), Kali Linux is based on Debian testing, which is currently `bullseye`. Hence, this PR will change the mapping of kali-rolling to Debian `bullseye` instead of `jessie`.
Currently, the mapping to `jessie` is causing issues with dependency resolution on attempts to install `nodejs`. Changing the entries in `/etc/apt/sources.list.d/nodesource.list` from `jessie` to `bullseye` resolves those issues, at least for me, and it makes sense to me to map Kali to the version of Debian it is based on.
Closes #1133

Map kali-rolling to Debian bullseye

---

rpm/setup
rpm/setup_0.10
rpm/setup_0.12
rpm/setup_10.x
rpm/setup_11.x
rpm/setup_12.x
rpm/setup_13.x
rpm/setup_14.x
rpm/setup_15.x
rpm/setup_4.x
rpm/setup_5.x
rpm/setup_6.x
rpm/setup_7.x
rpm/setup_8.x
rpm/setup_9.x
rpm/setup_current.x
rpm/setup_iojs_1.x
rpm/setup_iojs_2.x
rpm/setup_iojs_3.x
rpm/setup_lts.x
rpm/src/_setup.sh

'which' is not available at _all_ by default on Centos7
or Centos8 Docker images out of the box.
'command' is, and serves the same purpose in this case.
Example:
$ docker container run -it --rm centos:7
[root@a7ba6b6aca53 /]# command -v which
[root@a7ba6b6aca53 /]# command -v command
command
[root@a7ba6b6aca53 /]# exit
exit
$ docker container run -it --rm centos:8
[root@eca6d461750b /]# command -v which
[root@eca6d461750b /]# command -v command
command
[root@eca6d461750b /]# exit
exit

Prefer 'command' over 'which' for RPM distro scripts

---

README.md
test/README.md
test/test-docker.sh

The usage examples will otherwise fail silently unless someone has `pipefail` turned on.
```
-S, --show-error
When used with -s, --silent, it makes curl show an
error message if it fails.
-f, --fail
(HTTP) Fail silently (no output at all) on server errors.
```
Closes: https://github.com/nodesource/distributions/issues/1106

Use curl -fsSL flags consistently in usage examples

---

deb/src/_setup.sh

Uses keyring directory /usr/share/keyrings and "signed-by" as recommended by Debian.
https://wiki.debian.org/DebianRepository/UseThirdParty

Remove apt key

---

README.md
rpm/setup
rpm/setup_0.10
rpm/setup_0.12
rpm/setup_10.x
rpm/setup_11.x
rpm/setup_12.x
rpm/setup_13.x
rpm/setup_14.x
rpm/setup_15.x
rpm/setup_16.x
rpm/setup_4.x
rpm/setup_5.x
rpm/setup_6.x
rpm/setup_7.x
rpm/setup_8.x
rpm/setup_9.x
rpm/setup_current.x
rpm/setup_iojs_1.x
rpm/setup_iojs_2.x
rpm/setup_iojs_3.x
rpm/setup_lts.x
rpm/src/_setup.sh

Rocky 8 is another rebuild of RHEL8, similar to AlmaLinux.
Trivial change in regexp.
Fixes #1228

Add support for Rocky Linux 8.

---

README.md

Amends the `debmanual` instructions to remove the deprecated `apt-key` command, which is no longer used by the curlbash as of https://github.com/thepwagner/distributions/commit/1e1ee93cffc254f9fa71ca10465585496a7d148d#diff-9cfa1468c93fc18652e34a000f0c6614b0fa18f6f4887477ad9b0d36ca6a7eaa .
This brings the manual instructions inline with the automated instructions.
I tested with Debian11 (which coincidently [will be the last to include `apt-key`](https://manpages.debian.org/testing/apt/apt-key.8.en.html))

debmanual: avoid apt-key command

---

README.md
rpm/setup
rpm/setup_0.10
rpm/setup_0.12
rpm/setup_10.x
rpm/setup_11.x
rpm/setup_12.x
rpm/setup_13.x
rpm/setup_14.x
rpm/setup_15.x
rpm/setup_16.x
rpm/setup_17.x
rpm/setup_18.x
rpm/setup_4.x
rpm/setup_5.x
rpm/setup_6.x
rpm/setup_7.x
rpm/setup_8.x
rpm/setup_9.x
rpm/setup_current.x
rpm/setup_iojs_1.x
rpm/setup_iojs_2.x
rpm/setup_iojs_3.x
rpm/setup_lts.x
rpm/src/_setup.sh
rpm/src/build.sh

closes https://github.com/nodesource/distributions/issues/1372
The `/rpm/src` scripts were updated, so that v18 is present & considered current. `build.sh` was then used to auto-generate the setup files.

Support for Node v18

---

scripts/rpm/script_generator/base_script.sh
scripts/rpm/setup_18.x
scripts/rpm/setup_20.x
scripts/rpm/setup_21.x
scripts/rpm/setup_current.x
scripts/rpm/setup_lts.x

This PR solves #1748 which is a good improvement for the RPM repo.

chore: Remove yum update in favor of makecache

---

.github/workflows/deprecated.yaml
scripts/deb/setup_16.x
scripts/rpm/setup_16.x

Due to the amount of people still using Node.js 16 just simplified the installation script using the current template and decreased the wait time to 10 secs, a lot of people is monkey patching that sleep because is too long.

chore(node16): Refactor Node.js 16 script

---

.github/workflows/ci.yaml
.gitignore
README.md
scripts/rpm/script_generator/README.md
scripts/rpm/script_generator/base_script.sh
scripts/rpm/setup_18.x
scripts/rpm/setup_20.x
scripts/rpm/setup_21.x
scripts/rpm/setup_current.x
scripts/rpm/setup_lts.x

Tested with [rockylinux:9-minimal](https://hub.docker.com/_/rockylinux) and [redhat/ubi9-minimal](https://hub.docker.com/r/redhat/ubi9-minimal/tags) container images which both only contain [`microdnf`](https://github.com/rpm-software-management/microdnf) instead of `dnf` (or `yum`).

feat: Added support for using microdnf
