README.md
rpm/setup
rpm/test.sh

Hello,
I added some lines of code to support the latest version of CloudLinux 6.6 x86_64.  My apologies if I did not setup the pull request/repository correctly, as I am new to git.
Wes

added cloudlinux 6.6 support

---

test/test

Test fails if these aren't installed.

Need to check for gcc, make, libmpc-dev, and libcloog-isl-dev.

---

test/test

Reverts nodesource/distributions#24

Revert "Need to check for gcc, make, libmpc-dev, and libcloog-isl-dev."

---

deb/setup
deb/setup_0.10
deb/setup_0.12
deb/setup_dev
deb/setup_iojs_1.x
deb/setup_iojs_2.x
deb/src/_setup.sh

alias debian testing/stretch to jessie

---

deb/setup
deb/setup_0.10
deb/setup_0.12
deb/setup_dev
deb/setup_iojs_1.x
deb/setup_iojs_2.x
deb/setup_iojs_3.x

`cmd 2>&1 > /dev/null` wouldn't do the intended, stderr still points to the shell
remove [`UUOC`](http://www.smallo.ruhr.de/award.html)

setup: fix minor issues

---

deb/setup_5.x
deb/src/build.sh

also put "v4.x LTS Argon" into the v4.x setup script

added v5.x setup script

---

README.md
deb/setup
deb/setup_0.10
deb/setup_0.12
deb/setup_4.x
deb/setup_5.x
deb/setup_dev
deb/setup_iojs_1.x
deb/setup_iojs_2.x
deb/setup_iojs_3.x
deb/src/_setup.sh

Hi @chrislea and @rvagg 
PR to try add support for bunsenlabs Linux Hydrogen, based on Debian Jessie. This distro is the community continuation of great CrunchBang Linux !#
I Hope this PR is correct, and it's trying to solve #241 and #248 issues. If any change is needed, please tell me.
Thanks.

added support for bunsenlabs Hydrogen rc2

---

deb/setup_6.x

Adding support for Tanglu 3.0 chromodoris http://tanglu.org/

Support for Tanglu 3.0 chromodoris

---

rpm/setup
rpm/setup_0.10
rpm/setup_0.12
rpm/setup_4.x
rpm/setup_5.x
rpm/setup_iojs_1.x
rpm/setup_iojs_2.x
rpm/src/_setup.sh
rpm/test.sh

Fixes #256
pls review @retrohacker || @chrislea

allow 'redhat-release-client' in whatprovides

---

deb/setup
deb/setup_0.10
deb/setup_0.12
deb/setup_4.x
deb/setup_5.x
deb/setup_6.x
deb/setup_dev
deb/setup_iojs_1.x
deb/setup_iojs_2.x
deb/setup_iojs_3.x
deb/src/_setup.sh

explicitly reject armv6 before proceeding and giving bad binaries

---

README.md

Update the existing Table of Contents with: a Table of Contents heading, link to the FAQ, link to the Requested Distributions, and link to License. Additionally, follow the convention of having an `<a name=""></a>` tag for the Table of Contents links, and added tags to each of the listed sections.
Just an improvement that I feel would be beneficial. ❤️

Update Table of Contents in README.md

---

deb/src/_setup.sh

Tested working on my machine (amd64), NodeJS v9.x

Added Sparky Linux Nibiru to supported distro list

---

deb/src/_setup.sh

add deppin 15.5 unstable

---

deb/setup
deb/src/_setup.sh

Add Liquid Lemur, a Debian 9 variant, to setup.

Add Liquid Lemur to setup

---

README.md

Add FAQ entry for issue #657

---

README.md

https://rpm.nodesource.com/pub_10.x/fc/28/
https://rpm.nodesource.com/pub_8.x/fc/28/

Add Fedora 28 to readme

---

README.md

Fixed readme for BOSS6 support (pull request #645) which was merged

Added BOSS6

---

README.md

This was resolved as of #677 but the readme was not updated to mention it.

Update README.md to mention Linux Mint 19 support

---

.circleci/config.yml
deb/setup_12.x
deb/src/build.sh
rpm/setup_12.x
rpm/src/build.sh

Allow users to install Node.js 12

Add support for Node.js 12

---

README.md

Update docs for NodeJS 12.x

---

README.md

Issue #827 added support for 19.04 to the repositories, this just updates the readme to include it in the list.

Add 19.04 to list of supported Ubuntu versions

---

snap/snapcraft.yaml.sh

reflects current reality of the snap source

update snap generation script, remove npx from node 6, add yarnpkg alias

---

README.md
rpm/setup
rpm/setup_0.10
rpm/setup_0.12
rpm/setup_10.x
rpm/setup_11.x
rpm/setup_12.x
rpm/setup_13.x
rpm/setup_14.x
rpm/setup_15.x
rpm/setup_4.x
rpm/setup_5.x
rpm/setup_6.x
rpm/setup_7.x
rpm/setup_8.x
rpm/setup_9.x
rpm/setup_current.x
rpm/setup_iojs_1.x
rpm/setup_iojs_2.x
rpm/setup_iojs_3.x
rpm/setup_lts.x
rpm/src/_setup.sh

Support CentOS Stream 8

---

README.md

Mention where you can find RPM package signing key

---

README.md

urgently needed notice until https://github.com/nodesource/distributions/issues/1392#issuecomment-1134101584 is resolved

warn users of critical installation failures

---

README.md

Provide guidance in case a user installed the incorrect version, such as latest, vs LTS.

Add uninstall procedure for nodejs .deb packages

---

.github/ISSUE_TEMPLATE/distribution-support-request.md
.github/ISSUE_TEMPLATE/issue-bug-report.md

Create issue template to improve the problem resolution by obtaining enough information to debug and troubleshoot.

Update issue templates

---

README.md

@riosje good evening!
continuing in the spirit of https://github.com/nodesource/distributions/pull/1400...
see https://github.com/nodesource/distributions/issues/1433 and https://github.com/nodesource/distributions/issues/1402

Update README.md for Amazon Linux users

---

README.md

This PR has the following fixes:
1. correct `ommit` to `omit`
2. reframed a question for readability.
3. reframe a sentence for readability

Fix typos and sentence

---

README.md

- Fix typos
- Improve FAQ visualization

Fix and Readme Improvements

---

.circleci/config.yml
README.md

Fix #1640
* Update yum installation instructions

chore: Fix yum install instructions

---

.github/workflows/CI.yaml
README.md
scripts/nsolid_setup_deb.sh
scripts/nsolid_setup_rpm.sh

chore: Add installation scripts

chore: Add installation scripts

---

.circleci/config.yml
README.md

Updated readme instructions to make them easier to understand

Update Installation Instructions

---

scripts/deb/script_generator/base_script.sh
scripts/deb/setup_16.x
scripts/deb/setup_18.x
scripts/deb/setup_20.x
scripts/deb/setup_21.x
scripts/deb/setup_22.x
scripts/deb/setup_current.x
scripts/deb/setup_lts.x

This Solves https://github.com/nodesource/distributions/issues/1808
This fix improves the handling of folder deletion and creation.

fix: error handling while creating adn deleting folders

---

README.md

Small change to use github alert syntax as [described here](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts)

Use github note notation in README

---

.github/workflows/ci.yaml
README.md

doc: Format and add Ubuntu 24
